# 오류 처리

Parse에는 오류를 표시하고 코드에서 처리할 수 있는 간단한 패턴 몇 가지가 포함되어 있습니다.

두 가지 유형의 오류가 발생할 수 있습니다. 첫 번째는 SDK를 사용하는 방식으로 로직 오류를 처리하는 것입니다. `NSException`이 발생하면 이러한 유형의 오류가 발생합니다. 예를 들어, 다음 코드를 살펴볼 수 있습니다.

```objc
PFUser *user = [PFUser user];
[user signUp];
```

이 경우 먼저 필요한 속성(`username` 및 `password`)을 설정하지 않고 `signUp`을 호출했기 때문에 `NSInternalInconsistencyException`이 발생합니다.

두 번째 유형의 오류는 네트워크를 통해 Parse Cloud와 상호 작용할 때 발생합니다. 이러한 오류는 클라우드에 연결하는 문제나 요청된 작업을 수행하는 문제와 관련이 있습니다. 다른 예를 살펴보겠습니다.

```objc
- (void)getMyNote {
    PFQuery *query = [PFQuery queryWithClassName:@"Note"];
    [query getObjectInBackgroundWithId:@"thisObjectIdDoesntExist"
           target:self 
           selector:@selector(callbackForGet:error:)];
}
```

위 코드에서는 존재하지 않는 `objectId`가 지정된 개체를 가져오려고 합니다. Parse Cloud는 `code`에 설정된 오류 코드와 오류의 `userInfo`에 있는 메시지를 사용하여 오류를 반환합니다. 콜백에서 올바르게 처리하는 방법은 다음과 같습니다.

```objc
- (void)callbackForGet:(PFObject *)result error:(NSError *)error {
    if (result) {
        NSLog(@"Everything went fine!");
    } else {
        if ([error code] == kPFErrorObjectNotFound) {
            NSLog(@"Uh oh, we couldn't find the object!");
        } else if (error) {
            NSLog(@"Error: %@", [error userInfo][@"error"]);
        }
    }
}
```

기기에서 Parse Cloud에 연결할 수 없기 때문에 쿼리가 실패할 수도 있습니다. 다음은 기본적으로 동일하지만 이런 시나리오를 명확하게 처리하기 위한 추가 코드가 약간 더 포함된 콜백입니다.

```objc
- (void)callbackForGet:(PFObject *)result error:(NSError *)error {
    if (result) {
        NSLog(@"Everything went fine!");
    } else {
        if ([error code] == kPFErrorObjectNotFound) {
            NSLog(@"Uh oh, we couldn't find the object!");
            // Now also check for connection errors:
        } else if ([error code] == kPFErrorConnectionFailed) {
            NSLog(@"Uh oh, we couldn't even connect to the Parse Cloud!");
        } else if (error) {
            NSLog(@"Error: %@", [error userInfo][@"error"]);
        }
    }
}
```

콜백에서 `NSNumber`를 기대하는 경우 콜백의 `boolValue`에서 작업의 성공 여부를 알립니다. 예를 들어 `%{ParseObject}`의 `saveInBackgroundWithTarget:selector:` 메서드에 대한 콜백을 구현하는 방법은 다음과 같습니다.

```objc
- (void)callbackForSave:(NSNumber *)result error:(NSError *)error {
    if ([result boolValue]) {
        NSLog(@"Everything went fine!");
    } else {
        if ([error code] == kPFErrorConnectionFailed) {
            NSLog(@"Uh oh, we couldn't even connect to the Parse Cloud!");
        } else if (error) {
            NSLog(@"Error: %@", [error userInfo][@"error"]);
        }
    }
}
```

동기 메서드(백그라운드가 아닌)의 경우 오류 처리는 성공이나 실패를 나타내는 `NSNumber` 대신 실제 `BOOL`을 직접 받는다는 점만 제외하면 대체로 동일합니다.

기본적으로 모든 연결의 시간 제한이 10초이기 때문에 동기 메서드가 무기한으로 지연되지 않습니다.

가능한 모든 `NSError` 유형의 목록은 [API](/docs/ios) [API](/docs/osx)의 오류 코드 섹션을 참조하세요.
